server:
  port: 8080

spring:
  application:
    name: property-manager-service
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://pgsql.ankaref.com:5432/property_manager
    username: postgres
    password: Web1970+
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      accept_case_insensitive_properties: true

app:
  jwt:
    secret: "3ISZU0Pn2lgovzn2wTYkvPpv726xH2TYyFB2vqP8xes="
    access-exp: 3600
    issuer: "property-manager"


management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include: health,info,metrics,prometheus
  metrics:
    enable.jvm: true
    distribution.percentiles-histogram.http.server.requests: true